name: reddit_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  intl: ^0.16.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Medium.otf
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Semibold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Bold.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Black.otf
          weight: 900
    - family: Product-Sans
      fonts:
        - asset: assets/fonts/Product-Sans/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans/Product-Sans-Bold.ttf
          weight: 900
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-regular.ttf
